### ISSUE TITLE
Ajouter des images aux chiffres clés

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/admin#1578]
- [x] Back
- [x] Style extranet
- [x] Partie front en thème

![Capture d’écran 2024-01-29 à 12 07 00](https://github.com/noesya/osuny/assets/2088968/4b7179e9-9409-40b5-80cd-5e2d59403ab6)

**Comment by SebouChu** [comment]
Boulot en back fait sur la branche [`image-in-key-figures`](https://github.com/noesya/osuny/tree/image-in-key-figures)

```
- kind: block
    template: key_figures
    title: >-
      Key figures
    ranks:
      self: false
    data:
      description: >-

      figures:
        - number: 55
          unit: >-
            ans d'expertise
          description: >-

          image:
            id: "e770c025-f5bc-4f31-b771-aceb7b6a95bf"
            file: "e770c025-f5bc-4f31-b771-aceb7b6a95bf"
```

A faire

- [ ] Style extranet
- [ ] Partie front en thème
