### ISSUE TITLE
Image des personnes dans les fichiers statiques

### ISSUE THREAD

**Issue by alexisben** [osunyorg/admin#1657]
Dans le statique l'image d'une personne n'a pas le même format que les autres images : 

Dans example :
```
content/fr/persons/pierre-andre-boissinot.html:

image: "7d5b70f7-d336-4437-92ae-80af5a3aa6e9"
credit: >-
````

au lieu de 

```
content/fr/persons/pierre-andre-boissinot.html:

image:
  id: "7d5b70f7-d336-4437-92ae-80af5a3aa6e9"
  alt: ""
  credit: >-
````
