### ISSUE TITLE
Manque le rank des children dans le bloc Location

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/admin#1753]
```
- kind: block
    template: locations
    title: >-
      Liste des campus d'exemple Osuny
    ranks:
      self: 3
    data:
      locations:
        - slug: "iut-bordeaux-montaigne"
        - slug: "osuny"
```
