### ISSUE TITLE
Consolidation des fichiers statiques : path, slug, url, file

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/admin#1805]
## Pages
```
children:
  - "posts/_index.html"
  - "pages/blocks/_index.html"
  - "programs/_index.html"
  - "persons/_index.html"
  - "organizations/_index.html"
  - "diplomas/_index.html"
  - "publications/_index.html"
  - "pages/exemples/_index.html"
  - "events/_index.html"
  - "locations/_index.html"
  - "projects/_index.html"
```

## Campus (locations)

```
programs:
  - /gestion-administrative-et-commerciale-des-organisations/
diplomas:
  - name: >
      Bachelor Universitaire de Technologie
    path: bachelor-universitaire-de-technologie
    programs: 
    - label: >
        Gestion Administrative et Commerciale des Organisations
      path: "/formations/gestion-administrative-et-commerciale-des-organisations/"
      slug: "/gestion-administrative-et-commerciale-des-organisations/"

```

## papers
```
researchers:
  - "arnaud-levy"
```

## Fils d'ariane
```
breadcrumbs:
  - title: >-
      Accueil
    path: "/fr/"
  - title: >-
      Blocs
    path: "/fr/blocks/"
  - title: >-
      Les blocs de listes
    path: "/fr/blocks/blocs-de-liste/"
  - title: >-
      Les pages
```

### posts
```
      posts:
        - "2023/2023-03-04-referentiel-general-decoconception-de-services-numeriques-rgesn"
        - "2023/2023-08-02-proposition-de-loi-relative-a-la-responsabilite-des-medias-dans-le-traitement-des-enjeux-environneme"
```

### pages
```
      pages:
        - path: "/fr/blocks/tous-les-blocks/"
          slug: "tous-les-blocks"
          file: "pages/blocks/tous-les-blocks/_index.html"
          external: false
        - path: "/fr/blocks/tous-les-blocks-pleine-largeur/"
          slug: "tous-les-blocks-pleine-largeur"
          file: "pages/blocks/tous-les-blocks-pleine-largeur/_index.html"
          external: false
```

### persons
```
      persons:
        - slug: "alexis-benoit"
          external: false
          role: >-
            Co-fondateur et développeur front
        - slug: "olivia-simonet"
          external: false
          role: >-
            Développeuse front
```

### organizations
```
      organizations:
        - slug: "degrowth-journal"
          external: false
        - slug: "rose-primaire"
          external: false
        - slug: "universite-bordeaux-montaigne"
          external: false
        - slug: "mica"
          external: false
        - slug: "noesya"
          external: false
```

### programs
```
      programs:
        - path: "/coordination-de-projets-de-developpement-social-et-culturel/"
        - path: "/animation-sociale-et-socioculturelle/"
        - path: "/information-communication/developpement-de-sites-web-eco-concus-accessibles-et-responsables/"
```

### events
```
      events:
        - path: "/fr/agenda/2024-02-03-anne-charlotte-finel-respiro-1/"
          file: "events/2024-02-03-anne-charlotte-finel-respiro-1.html"
        - path: "/fr/agenda/2024-02-03-charbel-joseph-h-boutros-the-sun-is-my-only-ally/"
          file: "events/2024-02-03-charbel-joseph-h-boutros-the-sun-is-my-only-ally.html"
        - path: "/fr/agenda/2024-02-03-anne-charlotte-finel-respiro/"
          file: "events/2024-02-03-anne-charlotte-finel-respiro.html"
```

### projects
```
      projects:
        - slug: "degrowth-journal"
          file: "projects/2023-degrowth-journal.html"
        - slug: "dictionnaire-du-climat"
          file: "projects/2023-dictionnaire-du-climat.html"
        - slug: "alt-shift"
          file: "projects/2022-alt-shift.html"
```

## Situation souhaitée

```
        - path: "/fr/blocks/tous-les-blocks/"
          slug: "tous-les-blocks"
          file: "pages/blocks/tous-les-blocks/_index.html"
```

### path
- chemin complet
- incluant la langue
- avec un / final

### slug
- identifiant de l'objet
- sans parentèle 
- sans langue

### file
- chemin du fichier physique dans content
- avec ou sans la langue ?

**Comment by arnaudlevy** [comment]
Pour les blocs `posts`on a 
```
      posts:
        - "2023/2023-03-04-referentiel-general-decoconception-de-services-numeriques-rgesn"
        - "2023/2023-08-02-proposition-de-loi-relative-a-la-responsabilite-des-medias-dans-le-traitement-des-enjeux-environneme"
        - "2022/2022-12-01-les-cooperatives-energetiques-citoyennes-des-modeles-originaux-pour-plus-de-sobriete"
```

**Comment by arnaudlevy** [comment]
Pour les blocs `pages`

```

      pages:
        - path: "/fr/blocks/tous-les-blocks/"
          slug: "tous-les-blocks"
          file: "pages/blocks/tous-les-blocks/_index.html"
          external: false
        - path: "/fr/blocks/tous-les-blocks-pleine-largeur/"
          slug: "tous-les-blocks-pleine-largeur"
          file: "pages/blocks/tous-les-blocks-pleine-largeur/_index.html"
          external: false
        - path: "/fr/blocks/blocks-de-base/"
          slug: "blocks-de-base"
          file: "pages/blocks/blocks-de-base/_index.html"
          external: false
        - path: "/fr/blocks/blocks-narratifs/"
          slug: "blocks-narratifs"
          file: "pages/blocks/blocks-narratifs/_index.html"
          external: false
        - path: "/fr/blocks/blocs-de-liste/"
          slug: "blocs-de-liste"
          file: "pages/blocks/blocs-de-liste/_index.html"
          external: false
        - path: "/fr/blocks/blocks-techniques/"
          slug: "blocks-techniques"
          file: "pages/blocks/blocks-techniques/_index.html"
          external: false
        - path: "/fr/blocks/tous-les-blocks-pleine-largeur-1/"
          slug: "tous-les-blocks-pleine-largeur-1"
          file: "pages/blocks/tous-les-blocks-pleine-largeur-1/_index.html"
          external: false
        - path: "/fr/blocks/layout-large/"
          slug: "layout-large"
          file: "pages/blocks/layout-large/_index.html"
          external: false
        - path: "/fr/blocks/bloc-formation-plain-testclara1/"
          slug: "bloc-formation-plain-testclara1"
          file: "pages/blocks/bloc-formation-plain-testclara1/_index.html"
          external: false
```
