### ISSUE TITLE
Les blocs pages vides bloquent le site

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/admin#1991]
```
  - kind: block
    template: pages
    title: >-
      
    ranks:
      self: false
    data:
      show_main_description: false
      show_descriptions: true
      show_images: true
      layout: grid
      pages:
```

Il faudrait juste enlever de l'export
