### ISSUE TITLE
Retirer le layout d'un bloc post lorsqu'il est en mode "categories"

### ISSUE THREAD

**Issue by alexisben** [osunyorg/admin#2060]
Il faut réinitialiser la donnée du layout du bloc actualités s'il passe ou est en mode "Liste des catégories". Sinon ça peut péter l'affichage sur le thème.

**Comment by alexisben** [comment]
En fait il faudrait ces données là pour qu'elle soit clean : 

``` 
  - kind: block
    template: posts
    title: >-
      La liste des catégories
    ranks:
      self: 3
    data:
      mode: categories 
```
