### ISSUE TITLE
Bloc tableau : Ajouter un champ "légende"

### ISSUE THREAD

**Issue by alexisben** [osunyorg/admin#2111]
Il y a une erreur dans la donnée : la donnée `caption` renvoie le contenu de la transcription. C'est une erreur d'accessibilité, il faut ajouter un champ "Légende" qui servira de `caption` au tableau. De plus il ne faut pas de transcription mais une description pour les tableaux de données complexes.

~~Cela implique de migrer les data des blocs tableau, l'actuel `caption` doit devenir `summary` (RGAA : https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#5.2) et le nouveau champ `légende` doit porter la clé `caption` dans les fichiers statiques.~~

Il faut alors : 

1. Renommer "Transcription textuelle" en "Légende" (clé statique : `caption`)
2. Ajouter un champ "Description avancée" (clé statique : `summary`) avec une aide "Ce champ résume le contenu du tableau. Il est réservé aux [tableaux de données complexes](https://accessibilite.numerique.gouv.fr/methode/glossaire/#tableau-de-donnees-complexe), et est accessible aux lecteurs d'écran. "  
3. Corriger le fichier statique (voir exemple ci-dessous)

```
- kind: block
    template: datatable
    title: >-
      Il s'agit d'un tableau présentant l'équipe noesya
    ranks:
      self: false
    data:
      description: >-
        Il s'agit d'un tableau présentant l'équipe noesya
      columns: ["Prénom", "Nom", "Poste"]
      rows:
        - ["Magali", "Angles", "Doctorante"]
        - ["Alexis", "Benoit", "Dev front"]
        - ["Pierre-André", "Boissinot", "Dev back"]
      caption: >-
        L'équipe noesya
      summary: >-
        Une description avancée pour un tableau riche et/ou complexe.
```
