### ISSUE TITLE
Absence de layout pour le bloc "campus"

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/admin#2112]
En admin, on peut choisir d'afficher les campus en liste ou en grille, mais le static n'indique pas de layout :

```
- kind: block
    template: locations
    title: >-
      Campus — layout grille
    ranks:
      self: 3
      children: 4
    data:
      options:
        image: true
        summary: true

      locations:
        - slug: "iut-bordeaux-montaigne"
        - slug: "osuny"
```
