### ISSUE TITLE
Finir les catégories taxonomies

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/admin#2131]
https://github.com/osunyorg/admin/pull/2130

## Fonctions
- [x] Remettre l'arbre en fonction
- [x] Réparer les order
- [x] Créer des catégories liées aux formations pour les projets (idem actus et événements)
- [ ] Mettre en taxonomie la racine "Formations" (puisque c'en est une)

## Objets
- [ ] Communication::Extranet::Document::Category
- [ ] Communication::Extranet::Post::Category
- [x] Communication::Website::Portfolio::Category
- [x] Communication::Website::Post::Category
- [x] Communication::Website::Agenda::Category
- [x] Education::Program::Category
- [x] - [ ] University::Person::Category
- [x] University::Organization::Category

**Comment by arnaudlevy** [comment]
Faudrait-il une syntaxe plutôt comme ça @Olivia206 ?
Ce n'est plus un tableau, mais on peut accéder à `taxonomies.secteur.categories`.

```
project_categories:
  - "mode"
  - "design"
  - "et-accessible"
  - "gratuit"
taxonomies:
  secteur: 
    name: "Secteur"
    slug: "secteur"
    categories:
      - name: "Mode"
        permalink: ""
        file: "content/fr/projects_categories/mode/_index.html"
        path: "/mode/"
        slug: "mode"
  expertise:
    name: "Expertise"
    slug: "expertise"
    categories:
      - name: "Design"
        permalink: ""
        file: "content/fr/projects_categories/design/_index.html"
        path: "/design/"
        slug: "design"
```
