### ISSUE TITLE
Détection des liens externes dans le hero

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/admin#2283]
@MagaliAngles a repéré un truc sur Futur(s) : le bouton du héros ne détecte pas lorsqu'il est externe ou non, ce qui pose un souci d'accessibilité !

Voilà les données : 
```
header_cta:
  display: true
  label: >-
    Je commande FUTURs
  target: "https://buy.stripe.com/8wMfZH5Gz3uG2Ig4gs"
```

Est-ce qu'on pourrait avoir comme à d'autres endroits du statique l'info du target_blank true/false, s'il vous plait ?
