### ISSUE TITLE
Problème de data pour le format des liens

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/admin#2453]
En appliquant les `file` au menu (suite thème de https://github.com/osunyorg/admin/pull/2451), on s'est rendu compte que ça ne fonctionnait pas : 

![Capture d’écran 2024-11-25 à 16 09 24](https://github.com/user-attachments/assets/34fd4425-75ee-4734-8f90-353c511afc71)

C'est dû au fait qu'il y a deux formats de liens :

- avec ce format (backlinks) j'affiche "Actualités" correctement (dans"L'équipe" car ce sont des tests cracras) :
<img width="588" alt="Capture d’écran 2024-11-25 à 16 13 55" src="https://github.com/user-attachments/assets/8f6efd46-66a4-466b-b132-e7aec2113833">

- avec ce format (menu, fichier entier tel que donné dans le statique d'une page), on a un "nopPage" en voulant faire un `site.GetPage` :
<img width="624" alt="Capture d’écran 2024-11-25 à 16 09 50" src="https://github.com/user-attachments/assets/d2f12682-d6d4-4b13-a311-4a247072ec4d">

Il faudrait savoir s'il faut garder les deux et sur lequel se baser (actuellement pour que ça fonctionne dans le menu, il faut le chemin relatif), voire si un est faux.

Voilà le menu primary (j'ai changé la valeur du file pour que la différence soit visible) :

```
- title: L'association
  target: "/lassociation/"
  kind: page
      children:
            - title: Qui sommes-nous ?
              target: "/lassociation/qui-sommes-nous/"
              kind: page
              children: []
              file: "content/fr/pages/lassociation/qui-sommes-nous/_index.html"
            - title: L'équipe
              target: "/lassociation/l-association/"
              kind: page
              children: []
              file: "pages/lassociation/qui-sommes-nous/_index.html"
            - title: Le Club des partenaires
              target: "/lassociation/partenaires/"
              kind: page
              children: []
```

**Comment by arnaudlevy** [comment]
C'est pour ça qu'il faut merge ça !
https://github.com/osunyorg/admin/pull/2396

**Comment by Olivia206** [comment]
Actuellement on a ça dans `primary.yml` : 

```
---
title: Menu principal
items:
- title: À propos
  target: "/a-propos/"
  kind: page
  children:
  - title: Qui sommes-nous ?
    target: "/a-propos/qui-sommes-nous/"
    kind: page
    children: []
    file: content/fr/pages/a-propos/qui-sommes-nous/_index.html
```

Il nous faudrait le path : 
```---
...
  - title: Qui sommes-nous ?
    target: "/a-propos/qui-sommes-nous/"
    path: /pages/a-propos/qui-sommes-nous
    kind: page
    children: []
    file: content/fr/pages/a-propos/qui-sommes-nous/_index.html
```
