### ISSUE TITLE
Autoriser les cases vides dans les datatables

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/admin#2481]
https://www.numeriqueinteretgeneral.org/actualites/2023-09-29-label-numerique-en-communs/

```yaml
    data:
      description: >-
        

      columns: ["Label NEC", "NIG 1.1"]

      rows:
        - ["Accessible", "5.1 Accessible"]

        - ["Appropriable", "2.1 Possibilité d’appropriation"]

        - ["Éthique", "1.1 Besoins réels (beaucoup plus large)"]

        - ["_", "3.2 Gouvernance compatible (plus juridique)"]

        - ["_", "5.2 Simplicité"]

        - ["Ouvert", "3.1 Logiciel libre"]

        - ["Sécurisé", "7.3 Infrastructure et application sécurisées"]

        - ["Sobre", "1.3 En dessous des plafonds environnementaux (beaucoup plus large)"]

        - [".", "6.3 Frugalité"]

      caption: >-
        
```
