### ISSUE TITLE
Ajout des taxonomies dans les index des sections

### ISSUE THREAD

**Issue by alexisben** [osunyorg/admin#2537]
Par exemple ajouter dans `/content/fr/persons/_index.html` : 

```
taxonomies:
  - name: "Dev"
    slug: "dev"
    categories:
      - permalink: "/fr/equipe/categories/dev/front/"
        path: "/persons_categories/dev/front"
        slug: "dev/front"
        file: "content/fr/persons_categories/dev/front/_index.html"
        name: "Front"
  - name: "Langues"
    slug: "langues"
    categories:
  - name: "Nationalité"
    slug: "nationalite"
    categories:
free_categories:
  - permalink: "/fr/equipe/categories/design/"
    path: "/persons_categories/design"
    slug: "design"
    file: "content/fr/persons_categories/design/_index.html"
    name: "Design"
  - permalink: "/fr/equipe/categories/gestion-de-projet/"
    path: "/persons_categories/gestion-de-projet"
    slug: "gestion-de-projet"
    file: "content/fr/persons_categories/gestion-de-projet/_index.html"
    name: "Gestion de projet"
```
