### ISSUE TITLE
Traiter les catégories (free_categories) comme une taxo et afficher les taxonomies dans les index

### ISSUE THREAD

**Issue by alexisben** [osunyorg/admin#2538]
Pourquoi ne pas traiter les catégories libres comme une taxo dans les static ?

Par exemple : 
```
taxonomies:
  - name: "Catégories"
    slug: "categories"
    categories:
      - permalink: "/fr/actualites/a-la-une/"
        path: "/posts_categories/a-la-une"
        slug: "a-la-une"
        file: "content/fr/posts_categories/a-la-une/_index.html"
        name: "À la une"
  - name: "Offre de formation"
    slug: "offre-de-formation"
    categories:
  - name: "Type d'article"
    slug: "type-darticle"
    categories:
      - permalink: "/fr/actualites/type-darticle/billet/"
        path: "/posts_categories/type-darticle/billet"
        slug: "type-darticle/billet"
        file: "content/fr/posts_categories/type-darticle/billet/_index.html"
        name: "Billet"
      - permalink: "/fr/actualites/type-darticle/reportage/"
        path: "/posts_categories/type-darticle/reportage"
        slug: "type-darticle/reportage"
        file: "content/fr/posts_categories/type-darticle/reportage/_index.html"
        name: "Reportage"
```

**Comment by arnaudlevy** [comment]
C'est une très bonne idée, si on unifie le traitement. Là elles n'ont pas de parent, et il faut vérifier que l'ui est idem

**Comment by alexisben** [comment]
Ajouter les informations des taxonomies complètes dans l'index d'une section.

Par exemple dans `projects/index.html`, afficher toutes les taxonomies et catégories disponibles : 

```
taxonomies:
  - name: "Offre de formation"
    slug: "offre-de-formation"
    categories:
      - permalink: "/fr/projets/offre-de-formation/animation-sociale-et-socioculturelle/"
        path: "/projects_categories/offre-de-formation/animation-sociale-et-socioculturelle"
        slug: "offre-de-formation/animation-sociale-et-socioculturelle"
        file: "content/fr/projects_categories/offre-de-formation/animation-sociale-et-socioculturelle/_index.html"
        name: "Animation sociale et socioculturelle"
      - permalink: "/fr/projets/offre-de-formation/information-communication/"
        path: "/projects_categories/offre-de-formation/information-communication"
        slug: "offre-de-formation/information-communication"
        file: "content/fr/projects_categories/offre-de-formation/information-communication/_index.html"
        name: "Information - Communication"
  - name: "Project"
    slug: "project"
    categories:
       - [ ... ]
  - name: "Secteur"
    slug: "secteur"
    categories:
       - [ ... ]
  - name: "Catégories"
    slug: "categories"
    categories:
      - permalink: "/fr/projets/ui/"
        path: "/projects_categories/ui"
        slug: "ui"
        file: "content/fr/projects_categories/ui/_index.html"
        name: "UI"
```
