### ISSUE TITLE
Ajouter le `path` d'une taxonomie dans le static d'un objet

### ISSUE THREAD

**Issue by alexisben** [osunyorg/admin#2717]
Nous avons besoin de pouvoir récupérer l'objet de la taxonomie dans la single d'un objet.

Par exemple dans le static d'un post, ajouter la clé `path` de la taxo dans `taxonomies` :

```    path: "/pages_categories/types-de-contenus" ```
 
https://github.com/osunyorg/rennes-sandbox/blob/8a6d1a43ba8c54897893ce3c44f8d0b1e69a7421/content/fr/pages/fiches-pratiques/les-menus-des-creches/_index.html

```
taxonomies:
  - name: "Types de contenus"
    slug: "types-de-contenus"
    path: "/pages_categories/types-de-contenus"
    categories:
      - permalink: "/types-de-contenus/fiches-pratiques/"
        path: "/pages_categories/types-de-contenus/fiches-pratiques"
        slug: "types-de-contenus/fiches-pratiques"
        file: "content/fr/pages_categories/types-de-contenus/fiches-pratiques/_index.html"
        name: "Fiches pratiques"
```
