### ISSUE TITLE
Problème de préparation des quotes de name de catégories

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/admin#2726]
https://github.com/osunyorg/bordeauxmontaigne-controverses-ia-transhumanismes/blob/7b0a94c3cf1dbb33d92a4acc074b72533fb59524/content/fr/posts/_index.html

```yaml
      - permalink: "/productions/intelligence-artificielle/lia-doit-elle-avoir-une-moralite-programmee/"
        path: "/posts_categories/controverse/lia-doit-elle-avoir-une-moralite-programmee"
        slug: "controverse/lia-doit-elle-avoir-une-moralite-programmee"
        file: "content/fr/posts_categories/controverse/lia-doit-elle-avoir-une-moralite-programmee/_index.html"
        name: "L'IA doit-elle avoir une "moralité" programmée ?"
        count: 1
```
