### ISSUE TITLE
Staging : Manque le `path` dans le parent d'un événement

### ISSUE THREAD

**Issue by alexisben** [osunyorg/admin#2743]
La clé `path` de l'événement parent est absente : 

Testé sur les enfants de l'événement Arte concert : 

https://demo.osuny.dev/admin/fr/communication/websites/27ccefe4-753c-49b3-ae4d-31675fc53ce5/agenda/events/b3cfac89-e34c-45c3-9fbd-aabc1d9f0aab/

https://demo.osuny.dev/admin/fr/communication/websites/27ccefe4-753c-49b3-ae4d-31675fc53ce5/agenda/events/b3cfac89-e34c-45c3-9fbd-aabc1d9f0aab/static

```
parent:
  permalink: "/agenda/2025/arte-concert-festival/"
  path: "/"
  slug: "arte-concert-festival"
  file: ""
```
