### ISSUE TITLE
Bloc catégories : donnée manquante

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/admin#2807]
On reçoit ceci : 
```
  - kind: block
    template: categories
    title: >-
      Publics
    slug: >-
      publics
    ranks:
      base: 2
      self: 2
```

Il manque le rang des enfants, ce qu'on a par exemple ici dans un bloc de personnes : 
```
    ranks:
      base: 2
      self: 2
      children: 3
```

**Comment by Olivia206** [comment]
Aussi un souci sur la page d'accueil du Campus de la transition, le bloc cards (pages) a un titre de bloc de niveau 2 et des enfants de niveau 2 : 
```
- kind: block
    template: pages
    title: >-
      
    slug: >-
      
    ranks:
      base: 2
      children: 2
```

https://campus-transition.osuny.org/admin/fr/communication/websites/45ac0f99-6dfc-4c8c-951a-2bce7b444a13/pages/07bcac72-b836-43c0-a44a-22bbf6ac21cb/static
