### ISSUE TITLE
`path` cassé dans les blocs personnes

### ISSUE THREAD

**Issue by alexisben** [osunyorg/admin#2872]
Les clés des personnes sont manquantes dans les blocs personnes :

https://campus-transition.osuny.org/admin/fr/communication/websites/45ac0f99-6dfc-4c8c-951a-2bce7b444a13/pages/41318b7a-ddb3-4e10-8b7a-989490d0b27d/static

https://site.campus-transition.osuny.site/fr/a-propos/equipe/

```
persons:
        - permalink: ""
          path: "/"
          slug: "adrien-burdy"
          file: ""
          role: >-
            

        - permalink: "/fr/a-propos/equipe/arthur-croizier/"
          path: "/persons/arthur-croizier"
          slug: "arthur-croizier"
          file: "content/fr/persons/arthur-croizier.html"
          role: >-
            

        - permalink: ""
          path: "/"
          slug: "benoit-halgan"
          file: ""
          role: >-
            

        - permalink: ""
          path: "/"
          slug: "clement-martel"
          file: ""
          role: >-
            

        - permalink: ""
          path: "/"
          slug: "clemence-pichon"
          file: ""
          role: >-
            

        - permalink: "/fr/a-propos/equipe/anaelle-xxx/"
          path: "/persons/anaelle-xxx"
          slug: "anaelle-xxx"
          file: "content/fr/persons/anaelle-xxx.html"
          role: >-
```
