### ISSUE TITLE
Header CTA

### ISSUE THREAD

**Issue by alexisben** [osunyorg/admin#2952]
Au lieu d'avoir `header_cta.display : false`, laisser `header_cta` vide.

Actuel : 

```
header_cta:
  display: false
  label: >-
    
  target: ""
  external: false
```

Attendu : 
```
header_cta:
  
```

Cela évite de surcharger les partiels de vérification supplémentaire sur le bouton.
